services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no diretório /app do contêiner
      # para que as alterações no código sejam refletidas sem precisar reconstruir a imagem.
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000